apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: thumbnail-result
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
    - name: storageAccount
      secretKeyRef:
        name: storageAccount
    - name: storageAccessKey
      secretKeyRef:
        name: storageAccountKey
    - name: queue
      value: "thumbnail-result"
#   When using Azurite, uncomment the next two lines to point Dapr to its Azure Queue Storage endpoint.
#    - name: queueEndpointUrl
#      value: "http://localhost:10001/devstoreaccount1/thumbnail-request"

auth:
  secretStore: dev-secrets