openapi: 3.0.1
info:
  title: Contoso Ads
  description: ''
  version: '1.0'
servers:
  - url: https://contosoads-apim.azure-api.net/contoso
paths:
  /ads:
    get:
      summary: GetAds
      operationId: getads
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]